name: Unlock-NetEaseMusic

on:
  schedule:
    - cron: "37 */8 * * *" # 每 8 小时运行一次
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Chrome (latest)
        run: |
          echo "Installing Google Chrome..."
          choco install googlechrome -y
          echo "✅ Google Chrome installed."

      - name: Show installed Chrome version
        shell: pwsh
        run: |
          echo "Checking installed Chrome version..."
          if (Test-Path "C:\Program Files\Google\Chrome\Application\chrome.exe") {
              & "C:\Program Files\Google\Chrome\Application\chrome.exe" --version
          } else {
              echo "❌ Chrome not found!"
              exit 1
          }

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unlock script
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          PYTHONIOENCODING: utf-8
          PYTHONLEGACYWINDOWSSTDIO: utf-8
        run: |
          echo "Running auto_login.py..."
          python auto_login.py || echo "⚠️ Script failed, but continuing for artifact upload"

      - name: Upload debug screenshots (if any)
        uses: actions/upload-artifact@v4
        with:
          name: debug-screenshots
          path: |
            debug_iframe.png
            runtime_error.png
          if-no-files-found: ignore
